# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stability_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beam',
            name='Beam_Height',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='beam',
            name='Beam_Moment',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='beam',
            name='Beam_Shear',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='beam',
            name='Beam_Width',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='column',
            name='Column_Axial',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='column',
            name='Column_Thickness',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='column',
            name='Column_Width',
            field=models.FloatField(max_length=10),
        ),
    ]
